### ISSUE TITLE
Is there a way to get timestamps for each utterance?

### ISSUE THREAD

**Issue by terrykwon** [jacksonllee/pylangacq#10]
`.utterances()` just seems to return the list of string utterances. Is there a way to get the timestamp of each? I couldn't find a suitable method from the documentation.

**Comment by jacksonllee** [comment]
Hello, currently there isn't a method that conveniently gets you the parsed timestamp. It'd be a good feature to implement -- I'll be able to get to this after having refactored the codebase more substantially for #12.

**Comment by terrykwon** [comment]
@jacksonllee Thanks for the reply. I've been using the method in the `_SingleReader` class and it seems to be working quite well. Hope the feature gets officially added soon!

**Comment by jacksonllee** [comment]
Apologies for the long silence. I've just released [v0.13.0](https://pypi.org/project/pylangacq/0.13.0/). I have rewritten the whole `Reader` class, with a fair amount of breaking changes ([changelog](https://pylangacq.org/changelog.html#)). The private class `_SingleReader` no longer exists. For the time marks, they are now directly available as the attribute `time_marks` of the new `Utterance` class objects, documentation [here](https://pylangacq.org/transcriptions.html#time-marks). I'm closing this issue as resolved. Please let me know if you have any questions.
