### ISSUE TITLE
Does the current version support other languages? Thanks:)

### ISSUE THREAD

**Issue by PolarBearOrz** [jacksonllee/pylangacq#11]
Hi, I am working on the Childes corpora for a cross-lingual study and I find this tool very useful. 

I wonder if the current version supports other languages like Chinese and German, as I want to implement the language development measures through your api as well.

Thank you very much:)

**Comment by jacksonllee** [comment]
Hello, yes pylangacq should support CHILDES corpora out of the box; I have used pylangacq to parse French and Spanish CHILDES myself. If something doesn't work, please file additional tickets with details.
