### ISSUE TITLE
Handle [/-]: Error on reading Rollins corpus

### ISSUE THREAD

**Issue by mitjanikolaus** [jacksonllee/pylangacq#13]
Hi there! I was trying to load the [rollins corpus](https://childes.talkbank.org/access/Eng-NA/Rollins.html), but got the following exception:

```
Traceback (most recent call last):
  File "DIR/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5ae97c714e2e>", line 1, in <module>
    runfile('DIR/load_rollins_speech_acts.py', wdir='DIR')
  File "/snap/pycharm-professional/218/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/snap/pycharm-professional/218/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "DIR/load_rollins_speech_acts.py", line 4, in <module>
    transcripts = pylangacq.read_chat('data/Rollins/*.cha')
  File "DIR/lib/python3.7/site-packages/pylangacq/chat.py", line 53, in read_chat
    return Reader.from_chat_files(*filenames, **kwargs)
  File "DIR/lib/python3.7/site-packages/pylangacq/chat.py", line 165, in from_chat_files
    return cls(*filenames, **kwargs)
  File "DIR/lib/python3.7/site-packages/pylangacq/chat.py", line 114, in __init__
    self._reset_reader(*self._input_filenames)
  File "DIR/lib/python3.7/site-packages/pylangacq/chat.py", line 222, in _reset_reader
    self._fname_to_reader[fn] = _SingleReader(fn, encoding=self.encoding)
  File "DIR/lib/python3.7/site-packages/pylangacq/chat.py", line 944, in __init__
    self._all_tagged_sents = self._create_all_tagged_sents()
  File "DIR/lib/python3.7/site-packages/pylangacq/chat.py", line 1651, in _create_all_tagged_sents
    self.filename(), pformat(tiermarker_to_line), utterance
ValueError: cannot align the utterance and %mor tiers:
Filename: DIR/data/Rollins/cc09.cha
Tiers --
{'%gra': '1|0|ROOT 2|3|DET 3|1|OBJ 4|1|PUNCT',
 '%mor': 'v|see det:art|the n|baby .',
 'MOT': "<and that's> [/-] see the baby . \x15106765_109490\x15"}
Cleaned-up utterance --
and that's see the baby .
```

It seems like the utterance and %mor tiers indeed don't align, but is there a way of reading the file anyways? Thanks for your help!

**Comment by jacksonllee** [comment]
Hello @mitjanikolaus , thank you for reporting the issue. It looks like pylangacq didn't correctly handle `[/-]` (for "False Start Without Retracing", [from the CHAT manual](https://talkbank.org/manuals/CHAT.pdf#page=78) accessed 2020-11-16); I've taken the liberty of updating the title of this GitHub issue. Whatever comes before and including `[/-]` should have been dropped in the cleaned utterance. I've just pushed a commit to the master branch that should fix the issue. For now, you can get this updated version of pylangacq by pip-installing from the GitHub source directly and it should read the Rollins corpus without issues (I've tested this myself):

```bash
pip install --force-reinstall git+https://github.com/jacksonllee/pylangacq@master#egg=pylangacq
```

If for whatever reason this workaround of pip-installing from GitHub source doesn't work for you, then another (less convenient) way to make it work is to directly edit the relevant parts of the Rollins corpus before reading it in through pylangacq. There are four places in the Rollins corpus where `[/-]` raised the issue you reported, and removing the parts indicated below in the respective CHAT data files would avoid the issue.

File: `cc09.cha`
Utterance: `<and that's> [/-] see the baby .`
Remove: `<and that's> [/-]`

File: `ma12.cha`
Utterance: `can you do your little fish [/-] &-uh kisses .`
Remove: `fish [/-]`

File: `ma12.cha`
Utterance: `clown oh it's a cl [/-] soft .`
Remove: `cl [/-]`

File: `st09.cha`
Utterance: `(..) <take> [/-] that one doesn't fit on next „ does it ?`
Remove: `<take> [/-]`

Hope this helps!

**Comment by mitjanikolaus** [comment]
Installed the new version from source and it works, thanks a lot!

**Comment by jacksonllee** [comment]
Glad to hear the fix worked! Closing this ticket as resolved.
