### ISSUE TITLE
Expose Immediate Word Repetitions

### ISSUE THREAD

**Issue by dleve123** [jacksonllee/pylangacq#14]
👋 – thanks so much for the awesome library.

I was wondering there's a way to extract out repeated words from CHAT files.

Seems like your cleaning routine scrubs away this important bit of information, which seems pretty critical for analyses that might want to include repetition-rooted features:

https://github.com/jacksonllee/pylangacq/blob/master/pylangacq/util.py#L116

Is this information stored off somewhere else? Any recommendations here?

**Comment by jacksonllee** [comment]
Hello, yes, the tiers in CHAT data before all the parsing and scrubbing are available from the `index_to_tiers` method of a `Reader` object.

```python
In [1]: import pylangacq as pla

In [2]: corpus = pla.read_chat("path/to/your/chat/files")

In [3]: corpus.index_to_tiers()
Out[3]:
# Returns a dict.
# The keys are absolute file paths of the CHAT files.
# The values are dicts, where each of these dicts is a map from some integer index to the tiers I think you're looking for.
```

Does this help?

**Comment by dleve123** [comment]
Yes this does – from here I could write my own parsing code to count immediate repetitions. Just to confirm though, this information isn't directly explicitly exposed via the package's APIs?

**Comment by jacksonllee** [comment]
The `index_to_tiers` method is the only way that the unparsed data is exposed via the `Reader` API. (Internally, all the other "higher" level methods depend on the data structure that the private version of this `index_to_tiers` method creates, and so there's no need to have another way to expose unparsed data.)

**Comment by jacksonllee** [comment]
Closing this ticket as the question has been addressed. Thanks!
