### ISSUE TITLE
IPSyn level calculation is not accurate

### ISSUE THREAD

**Issue by dcanones** [jacksonllee/pylangacq#15]
Hi!

It seems like the IPSyn level calculation is not accurate. It takes punctuation marks (e.g. [.]) as a full valid word, triggering some of the IPSyn rules and increasing its value artificially.

**Comment by jacksonllee** [comment]
Hello, do you have more concrete examples and details (e.g., which CHILDES dataset you used, which IPSyn rules)?

**Comment by jacksonllee** [comment]
I've just looked at [the IPSyn code](https://github.com/jacksonllee/pylangacq/blob/a18c6de290a0cd806f340f93a431f9d9730eadc2/pylangacq/measures.py#L67). All the 56 items are based on the dependency graph of a given utterance and rely on morphological and syntactic/semantic information (e.g., part-of-speech tags), and there doesn't seem to be anything related to punctuation marks.

I'm closing this ticket for now -- we can reopen it if further info like which IPSyn items specifically are problematic and/or relevant CHILDES data is available for debugging.
