### ISSUE TITLE
“Multiple Repetition” marker means repetitions of a single word

### ISSUE THREAD

**Issue by hellolzc** [jacksonllee/pylangacq#2]
Hi，I find a bug.
The CHAT Transcription Format ( https://talkbank.org/manuals/CHAT.pdf ) says

![image](https://user-images.githubusercontent.com/20534613/51439323-6514bf80-1cf3-11e9-9dc8-da036ebbdaa5.png)

However, the code now regard this symbol as reprtitions of a sentence.

Thanks for any help.

**Comment by jacksonllee** [comment]
Apologies for the long silence. I've just released [v0.13.0](https://pypi.org/project/pylangacq/0.13.0/), with a fix for this issue. I'm closing this issue as resolved. Please let me know if you have any questions.
